personal:
  name: Nguyen Huu Quan - Titus
  title: Fullstack Software Engineer
  references:
    gmail: quannh.netalik@gmail.com
    phone:  +64 34 969 0608
    skype: xCAO5sKxlrlz
    github: quannh-netalik
    linkedin: quan-netalik
    npx: qnh
    portfolio: https://www.canva.com/design/DAEcF8wVBxA/8KDnSQ5vscGb53vHrxIg8w/view?utm_content=DAEcF8wVBxA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton#2

reference-sites:
  linkedinRef: https://www.linkedin.com/in/
  githubRef: https://github.com/
  skypeRef: https://join.skype.com/invite/
